[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
    "forge-std/=lib/forge-std/src/",
    "halmos-cheatcodes/=lib/openzeppelin-contracts/lib/halmos-cheatcodes/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "@hedera-smart-contracts/=lib/hedera-smart-contracts/"
]

auto_detect_remappings = true
optimizer = true
optimizer_runs = 200
solc = "0.8.19"
evm_version = "paris"
via_ir = false
chain_id = 296  # Hedera Testnet Chain ID

# File system permissions
[[profile.default.fs_permissions]]
access = "read"
path = "./"

[[profile.default.fs_permissions]]
access = "write"
path = "./"

[profile.broadcast]
fs_permissions = [
  { access = "read", path = "./" },
  { access = "write", path = "./" }
]

# RPC Endpoints
[rpc_endpoints]
testnet = "${HEDERA_TESTNET_RPC}"

